### ISSUE TITLE
Update points where edges connect to connectors when nodes are dragged

### ISSUE THREAD

**Issue by orausch** [spcl/dace#206]
When a SDFG is rendered, it seems like the points where the arrows connect to connectors and nodes is chosen according to the direction of the edge:
![image](https://user-images.githubusercontent.com/22137236/79047668-6b54cb80-7c18-11ea-89a9-2b1addb1823a.png)

When nodes are dragged, the direction of the edge can change, but the connection point doesn't get recalculated, resulting in situations like the following:
![image](https://user-images.githubusercontent.com/22137236/79047710-a2c37800-7c18-11ea-981c-f217eba0ea17.png)
IMO it would be good to recalculate the connection points, so that, for example, the rightmost in connector of the tasklet connects to the left side of the connector, instead of the right side as before.

**Comment by tbennun** [comment]
Fixed in latest master.

**Comment by orausch** [comment]
FYI, the points should also update when the edge or the source of the edge is moved. Currently they do not, so situations like this can still occur: 
![image](https://user-images.githubusercontent.com/22137236/95865411-f39e5f80-0d66-11eb-8a51-c666d2780d0b.png)

Also, it might be nice to apply the same principle to AccessNodes so that the edges to cut across them like that.

**Comment by tbennun** [comment]
I disagree, this is an outgoing edge of `_b` and the structure might cause confusion IMO.
